name: backend

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Request & assemble data
      env:
        GHP: ${{ secrets.GHP }}
      run: go run main.go github.go util.go --numrepos 5000 --ghp $GHP -o repo-data.json
    - name: Upload repo-data.json
      uses: actions/upload-artifact@v2
      with:
        name: repo-data
        path: repo-data.json

  build-frontend:
    needs: build-backend
    uses: dodafin/octotrends/.github/workflows/frontend.yml@main
