name: Go

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'

jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        

    - name: Run
      env:
        GHP: ${{ secrets.GHP }}
      run: go run *.go --minstars 250 --ghp $GHP -o repo-data.json
    - name: Upload out.json
      uses: actions/upload-artifact@v2
      with:
        name: repo-data
        path: repo-data.json

  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - uses: actions/download-artifact@v2
      with:
        name: repo-data
    - run: mkdir src/data
    - run: mv ../repo-data.json src/data/repo-data.json
    - run: echo "{\"last_updated\":\"$(date +"%B %d, %Y, %-I:%M %p UTC")\"}" > src/data/last_updated.json
    - run: npm run build
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        echo 'octotrends.com' > ./build/CNAME
        npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
