name: Go

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'

jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        

    - name: Run
      env:
        GHP: ${{ secrets.GHP }}
      run: go run *.go --minstars 5000 --ghp $GHP -o repo-data.json
    - name: Upload out.json
      uses: actions/upload-artifact@v2
      with:
        name: repo-data
        path: repo-data.json




  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install

    - uses: actions/download-artifact@v2
      with:
        name: repo-data
    - run: mv ../repo-data.json src/out.json
    - run: npm run deploy
